server:
  port: 8989   #修改默认端口
  context-path: /springboot_class #用来指定项目名
  jsp-servlet:
    init-parameters:
      development: true  #开启jsp页面热部署功能
spring:
  mvc:
    view:
      prefix: / #前缀
      suffix: .jsp  #后缀
    #修改上传文件大小
  http:
    multipart:
      max-file-size: 20971520  #用来指定服务器端最大文件大小
      max-request-size: 209715200 #用来控制文件上传大小限制
      #配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_class?characterEncoding=UTF-8
    username: root
    password: root
    #配置mapper配置文件位置
mybatis:
  mapper-locations: classpath:com/sClass/mapper/*Mapper.xml
  #给当前包下的类起别名
  type-aliases-package: com.sClass.entity